apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: docker.io/raphaelassor5/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
  - image: docker.io/raphaelassor5/comments
    context: comments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '*.js'
        dest: .
  - image: docker.io/raphaelassor5/query
    context: query
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '*.js'
        dest: .
  - image: docker.io/raphaelassor5/posts
    context: posts
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '*.js'
        dest: .
  - image: docker.io/raphaelassor5/moderation
    context: moderation
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '*.js'
        dest: .
  - image: docker.io/raphaelassor5/event-bus
    context: event-bus
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '*.js'
        dest: .